### PR TITLE
Switch to GitHub actions

### PR DESCRIPTION
**Pull request by marcoow**
Travis has been an unpleasant experience recently and it's getting worse so this migrates to GitHub actions. Also all of our repos should ideally use the same service for easier maintenance anyway…

### CODE REVIEW

**Comment by marcoow** [comment]
I don't know why GitHub actions don't start here…

**Comment by Turbo87** [comment]
> I don't know why GitHub actions don't start here…

because the `master` branch doesn't have it enabled for PRs yet and the branch config in the file in this PR does not match the PR branch 😉

**Comment by marcoow** [comment]
@Turbo87 got it – added a temp commit so this can run once

**Comment by marcoow** [comment]
@patsy-issa before merging we should remove b87f7031086ac75a52a95c86e4753f233201ce98 again

**Review by patsy-issa — APPROVED** [review]
lgtm 👍

**Pull request merged**
