### PR TITLE
Use toggle-able agenda for each topic. Closes #50

### LINKED ISSUE #50: Reuse Aganda toggle from simplabs.com
introduced via simplabs/simplabs.github.io#57

### PR DESCRIPTION
**Pull request by ganeshbsub**

### CODE REVIEW

**Comment by ganeshbsub** [comment]
@marcoow Can we merge this, if its okay?

**Comment by ganeshbsub** [comment]
@marcoow can we merge this if it is okay?

**Comment by marcoow** [comment]
@ganeshbsub: can we make the button look like the submit button for the newsletter form (rounded corners, bold white font, change background to light blue on hover/active)? Still doesn't fit in with the rest of the design nicely.

**Comment by ganeshbsub** [comment]
Looks a bit in tune now. I'm not quite sure about the border when on hover though. Is that okay or should I change it to black/make it light blue?

**Comment by marcoow** [comment]
@ganeshbsub: I removed the border

**Pull request merged**
